RegistroCandidatos/Models/Candidato.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RegistroCandidatos.Models
{
	public enum NombreGenero
	{
        [Display(Name ="Masculino")]
		Masculino,

        [Display(Name = "Femenino")]
        Femenino,

        [Display(Name = "Otros")]
        Otros

    }
    //Este codigo activa el campo Cedula como unico aplicandole un indice
    [Index(nameof(Cedula), IsUnique = true)]
    public class Candidato
    {
        [Key, Required]
        public int ID_Candidato { get; set; }

        [Required(ErrorMessage = "La cedula es requerida.")]
        [Display(Name = "Cedula")]
        public string Cedula { get; set; }

        [Required(ErrorMessage = "Los nombres son requeridos.")]
        [Display(Name = "Nombres")]
        public string Nombres { get; set; }

        [Required(ErrorMessage = "Los apellidos son requeridos.")]
        [Display(Name = "Apellidos")]
        public string Apellidos { get; set; }

        [Required(ErrorMessage = "La fecha de nacimiento es requerida.")]
        [Display(Name = "Fecha de Nacimiento")]
        [DataType(DataType.Date)]
        public DateTime FechaDeNacimiento { get; set; }

        [Required(ErrorMessage = "El genero es requerido.")]
        public NombreGenero Genero { get; set; }

        [Display(Name ="Trabajo Actual")]
        public string TrabajoActual{ get; set; }


        //Este campo se manejara como un campo de moneda
        [Display(Name ="Expectativa Salarial")]
        public string ExpectativaSalarial { get; set; }
    }
}

RegistroCandidatos/Controllers/CandidatosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RegistroCandidatos.Data;
using RegistroCandidatos.Models;

namespace RegistroCandidatos.Controllers
{
    public class CandidatosController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CandidatosController(ApplicationDbContext context)
        {
            _db = context;
        }

        // GET: Candidatos
        public async Task<IActionResult> Index()
        {
              return View(await _db.Candidato.ToListAsync());
        }

		[HttpPost]
		public JsonResult Applicant()
		{
			int totalRecord = 0;
			int filterRecord = 0;
			var draw = Request.Form["draw"].FirstOrDefault();
			var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
			var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
			var searchValue = Request.Form["search[value]"].FirstOrDefault();
			int pageSize = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0");
			int skip = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0");
			var data = _db.Set<Candidato>()
				.Select(
				b => new
				{
					candidato_Id = b.ID_Candidato,
					nombres = b.Nombres,
					apellidos = b.Apellidos,
					cedula = Int64.Parse((b.Cedula.Replace("-", ""))).ToString("000-0000000-0"),
                    genero = b.Genero.ToString(),
					fechaDeNacimiento = b.FechaDeNacimiento.ToString("dd/MM/yyyy"),
					trabajoActual = b.TrabajoActual,
					expectativaSalarial = b.ExpectativaSalarial


				}).AsEnumerable();
			//get total count of data in table
			totalRecord = data.Count();
			// search data when search value found
			if (!string.IsNullOrEmpty(searchValue))
			{
				data = data.Where(x =>
				x.nombres.ToLower().Contains(searchValue.ToLower())
				|| x.apellidos.ToLower().Contains(searchValue.ToLower())
				|| x.cedula.ToLower().Contains(searchValue.ToLower())
				|| x.genero.ToString().ToLower().Contains(searchValue.ToLower())
				|| x.trabajoActual.ToString().ToLower().Contains(searchValue.ToLower())
				|| x.expectativaSalarial.ToString().ToLower().Contains(searchValue.ToLower()));
			}
			// get total count of records after search
			filterRecord = data.Count();
			//sort data
			if (!string.IsNullOrEmpty(sortColumn) && !string.IsNullOrEmpty(sortColumnDirection))
			{
				//data = data.OrderBy(x => sortColumn + " " + sortColumnDirection);
				data = data.OrderBy(x => string.Join(" ", sortColumn, sortColumnDirection));







			}
			//pagination
			var ListaCandidatos = data.Skip(skip).Take(pageSize).ToList();
			var returnObj = new
			{
				draw = draw,
				recordsTotal = totalRecord,
				recordsFiltered = filterRecord,
				data = ListaCandidatos
			};

			return Json(returnObj);



		}

		// GET: Candidatos/Details/5
		public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _db.Candidato == null)
            {
                return NotFound();
            }

            var candidato = await _db.Candidato
                .FirstOrDefaultAsync(m => m.ID_Candidato == id);
            if (candidato == null)
            {
                return NotFound();
            }

            return View(candidato);
        }

        // GET: Candidatos/Create
        public IActionResult Create()
        {
          
            return View();
        }

        // POST: Candidatos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID_Candidato,Cedula,Nombres,Apellidos,FechaDeNacimiento,Genero,TrabajoActual,ExpectativaSalarial")] Candidato candidato)
        {


			if (CedulaExists(candidato.Cedula))
			{

				ModelState.AddModelError(String.Empty, "Esta cedula ya ha sido registrada");
				return View(candidato);

			}

			else if (ModelState.IsValid)
            {
                
				_db.Add(candidato);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(candidato);
        }

        // GET: Candidatos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _db.Candidato == null)
            {
                return NotFound();
            }

            var candidato = await _db.Candidato.FindAsync(id);
            if (candidato == null)
            {
                return NotFound();
            }
            return View(candidato);
        }

        // POST: Candidatos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID_Candidato,Cedula,Nombres,Apellidos,FechaDeNacimiento,Genero,TrabajoActual,ExpectativaSalarial")] Candidato candidato)
        {
            if (id != candidato.ID_Candidato)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
					_db.Update(candidato);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CandidatoExists(candidato.ID_Candidato))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(candidato);
        }

        // GET: Candidatos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _db.Candidato == null)
            {
                return NotFound();
            }

            var candidato = await _db.Candidato
                .FirstOrDefaultAsync(m => m.ID_Candidato == id);
            if (candidato == null)
            {
                return NotFound();
            }

            return View(candidato);
        }

        // POST: Candidatos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_db.Candidato == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Candidato'  is null.");
            }
            var candidato = await _db.Candidato.FindAsync(id);
            if (candidato != null)
            {
				_db.Candidato.Remove(candidato);
            }
            
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CandidatoExists(int id)
        {
          return _db.Candidato.Any(e => e.ID_Candidato == id);
        }

		private bool CedulaExists(string cedula)
		{

			return _db.Candidato.Any(c => c.Cedula == cedula);


		}
	}
}

RegistroCandidatos/Views/Candidatos/Create.cshtml
@model RegistroCandidatos.Models.Candidato

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div>
    @if (!ViewData.ModelState.IsValid)
    {
        <div class="alert alert-warning alert-dismissible fade show w-100" style="height:4.5rem;" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            @Html.ValidationSummary(false, "Ha ocurrido un error: ")
        </div>
    }
</div>
<div class="row card mt-5">
    <h4 class="text-verdeReservas text-uppercase mt-3 ms-5 ps-5">Registro Candidatos</h4><br />


    <form asp-action="Create" class="container ms-5 ps-5">
        <div asp-validation-summary="None" class="text-danger"></div>
        <div class="row">
            <div class="d-flex col-12 mb-2">
                <div class="col-5 me-3">
                    <div class="form-group">
                        <label asp-for="Nombres" class="control-label text-verdeReservas"></label><span class="text-danger">*</span>
                        <input asp-for="Nombres" class="form-control" placeholder="Ej: Juan Alberto"/>
                        <span asp-validation-for="Nombres" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-5">
                    <div class="form-group">
                        <label asp-for="Apellidos" class="control-label text-verdeReservas"></label><span class="text-danger">*</span>
                        <input asp-for="Apellidos" class="form-control" placeholder="Ej: Perez Garcia"/>
                        <span asp-validation-for="Apellidos" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="d-flex col-lg-12 mb-2">
                <div class="col-5 me-3">
                    <div class="form-group">
                        <label asp-for="Cedula" class="control-label text-verdeReservas"></label><span class="text-danger">*</span>
                        <input asp-for="Cedula" class="form-control" id="nCedula" placeholder="Ej: 001-0022548-2"/>
                        <span asp-validation-for="Cedula" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-5">
                    <div class="form-group">
                        <label asp-for="FechaDeNacimiento" class="control-label text-verdeReservas"></label><span class="text-danger">*</span>
                        <input asp-for="FechaDeNacimiento" class="form-control" />
                        <span asp-validation-for="FechaDeNacimiento" class="text-danger"></span>
                    </div>
                </div>

            </div>
            <div class="d-flex col-lg-12 mb-2">
                <div class="col-5 me-3">
                    <div class="form-group">
                        <label asp-for="Genero" class="control-label text-verdeReservas"></label><span class="text-danger">*</span>
                        <select asp-for="Genero" class="form-control" asp-items="@Html.GetEnumSelectList<NombreGenero>()">
                            <option selected disabled value="">Seleccione un genero</option>
                        </select>
                        <span asp-validation-for="Genero" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-5">
                    <div class="form-group">
                        <label asp-for="TrabajoActual" class="control-label text-verdeReservas"></label>
                        <input asp-for="TrabajoActual" class="form-control" placeholder="Ej: Desarrollador Web"/>
                        <span asp-validation-for="TrabajoActual" class="text-danger"></span>
                    </div>
                </div>

            </div>

            <div class="d-flex col-lg-12 mb-2">
                <div class="col-5 me-3">
                    <div class="form-group">
                        <label asp-for="ExpectativaSalarial" class="control-label text-verdeReservas"></label>
                        <div class="input-group">
                            <span class="input-group-text">RD$</span>
                            <input asp-for="ExpectativaSalarial" class="form-control" id="ExSalarial"  />
                        </div>
                        <span asp-validation-for="ExpectativaSalarial" class="text-danger"></span>
                    </div>
                </div>

            </div>


        </div>
        <br>
        <div class="form-group col-sm-12 col-md-12 col-lg-12">
            <button type="submit" class="btn btn-verdeReservas col-sm-2 col-md-2 col-lg-2"><i class="fa-regular fa-floppy-disk me-2"></i>Añadir</button>
        </div>

    </form>
    <br />


</div>

<div class="mt-3">
    <a asp-action="Index" class="btn btn-verdeReservas col-sm col-sm-2 col-md col-md-2 col-lg col-lg-2"><i class="fa-regular fa-circle-left me-2"></i>Volver</a>
</div>



@section Scripts {

    <script type="text/javascript">


        let MontoSolic = SimpleMaskMoney.setMask('#ExSalarial', {
            prefix: '',
            suffix: '',
            fixed: true,
            fractionDigits: 2,
            decimalSeparator: '.',
            thousandsSeparator: ',',
            emptyOrInvalid: () => {
                return this.SimpleMaskMoney.args.fixed
                    ? `0${this.SimpleMaskMoney.args.decimalSeparator}00`
                    : `_${this.SimpleMaskMoney.args.decimalSeparator}__`;
            }
        });

        var cedulaMask = IMask(
            document.getElementById('nCedula'), {
            mask: '000-0000000-0'
        });

        console.log("los scripts sirven");

        function removeMask() {

            var cedulaMask = IMask(
                document.getElementById('nCedula'), {
                mask: '00000000000'
            });

        }

    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

RegistroCandidatos/Views/Candidatos/Delete.cshtml
@model RegistroCandidatos.Models.Candidato

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container mt-5 ">
    <div class="col-lg-8">
        <div class="card mb-4">
            <div class="card-header"><h5 class="text-verdeReservas">Confirma que quiere eliminar este candidato?</h5></div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-5">
                        <strong class="text-verdeReservas mb-0">@Html.DisplayNameFor(model => model.Nombres)</strong>
                    </div>
                    <div class="col-sm-7">
                        <p class="text-muted mb-0">@Html.DisplayFor(model => model.Nombres)</p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-5">
                        <strong class="text-verdeReservas mb-0">@Html.DisplayNameFor(model => model.Apellidos)</strong>
                    </div>
                    <div class="col-sm-7">
                        <p class="text-muted mb-0">@Html.DisplayFor(model => model.Apellidos)</p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-5">
                        <strong class="text-verdeReservas mb-0">@Html.DisplayNameFor(model => model.Cedula)</strong>
                    </div>
                    <div class="col-sm-7">
                        <p class="text-muted mb-0">@Html.DisplayFor(model => model.Cedula)</p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-5">
                        <strong class="text-verdeReservas mb-0">@Html.DisplayNameFor(model => model.FechaDeNacimiento)</strong>
                    </div>
                    <div class="col-sm-7">
                        <p class="text-muted mb-0">@Html.DisplayFor(model => model.FechaDeNacimiento)</p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-5">
                        <strong class="text-verdeReservas mb-0">@Html.DisplayNameFor(model => model.Genero)</strong>
                    </div>
                    <div class="col-sm-7">
                        <p class="text-muted mb-0">@Html.DisplayFor(model => model.Genero)</p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-5">
                        <strong class="text-verdeReservas mb-0">@Html.DisplayNameFor(model => model.TrabajoActual)</strong>
                    </div>
                    <div class="col-sm-7">
                        <p class="text-muted mb-0">@Html.DisplayFor(model => model.TrabajoActual)</p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-5">
                        <strong class="text-verdeReservas mb-0">@Html.DisplayNameFor(model => model.ExpectativaSalarial)</strong>
                    </div>
                    <div class="col-sm-7">
                        <p class="text-muted mb-0">@Html.DisplayFor(model => model.ExpectativaSalarial)</p>
                    </div>
                </div>


            </div>
        </div>


    </div>




    <form asp-action="Delete">
        <input type="hidden" asp-for="ID_Candidato" />
        <a class="btn btn-verdeReservas col-md-2" asp-action="Index"><i class="fa-regular fa-circle-left me-2"></i>Volver</a>
        <button type="submit" class="btn btn-danger"><i class="fa-solid fa-trash btn btn-danger" id="btnEliminar"></i>Borrar</button>
    </form>

</div>

RegistroCandidatos/Views/Candidatos/Details.cshtml
@model RegistroCandidatos.Models.Candidato

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-5 ">
    <div class="col-lg-8">
        <div class="card mb-4">
            <div class="card-header"><h5 class="text-azulmapre text-uppercase">Informacion Solicitante</h5></div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-5">
                        <strong class="text-verdeReservas mb-0">@Html.DisplayNameFor(model => model.Nombres)</strong>
                    </div>
                    <div class="col-sm-7">
                        <p class="text-muted mb-0">@Html.DisplayFor(model => model.Nombres)</p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-5">
                        <strong class="text-verdeReservas mb-0">@Html.DisplayNameFor(model => model.Apellidos)</strong>
                    </div>
                    <div class="col-sm-7">
                        <p class="text-muted mb-0">@Html.DisplayFor(model => model.Apellidos)</p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-5">
                        <strong class="text-verdeReservas mb-0">@Html.DisplayNameFor(model => model.Cedula)</strong>
                    </div>
                    <div class="col-sm-7">
                        <p class="text-muted mb-0">@Html.DisplayFor(model => model.Cedula)</p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-5">
                        <strong class="text-verdeReservas mb-0">@Html.DisplayNameFor(model => model.FechaDeNacimiento)</strong>
                    </div>
                    <div class="col-sm-7">
                        <p class="text-muted mb-0">@Html.DisplayFor(model => model.FechaDeNacimiento)</p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-5">
                        <strong class="text-verdeReservas mb-0">@Html.DisplayNameFor(model => model.Genero)</strong>
                    </div>
                    <div class="col-sm-7">
                        <p class="text-muted mb-0">@Html.DisplayFor(model => model.Genero)</p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-5">
                        <strong class="text-verdeReservas mb-0">@Html.DisplayNameFor(model => model.TrabajoActual)</strong>
                    </div>
                    <div class="col-sm-7">
                        <p class="text-muted mb-0">@Html.DisplayFor(model => model.TrabajoActual)</p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-5">
                        <strong class="text-verdeReservas mb-0">@Html.DisplayNameFor(model => model.ExpectativaSalarial)</strong>
                    </div>
                    <div class="col-sm-7">
                        <p class="text-muted mb-0">@Html.DisplayFor(model => model.ExpectativaSalarial)</p>
                    </div>
                </div>
                
                
            </div>
        </div>


    </div>




    <div class="mt-3">
        <a class="btn btn-verdeReservas col-2" asp-action="Edit" asp-route-id="@Model?.ID_Candidato"><i class="fa-solid fa-pen-to-square me-2"></i>Editar informacion</a> |
        <a class="btn btn-verdeReservas col-2" asp-action="Index"><i class="fa-regular fa-circle-left me-2"></i>Volver</a>
    </div>

</div>

RegistroCandidatos/Views/Candidatos/Index.cshtml
@model IEnumerable<RegistroCandidatos.Models.Candidato>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<h3 class="text-verdeReservas">CANDIDATOS BANRESERVAS</h3>
<hr />

<p>
    <a asp-action="Create" class="text-uppercase btn btn-verdeReservas"><i class="fa-solid fa-user-plus me-2"></i>Añadir Nuevo</a>
</p>

<br />
<br />



<div class="row">

    <table id="tbCandidatos" class="table table-striped  w-100 border">
        <thead>
            <tr class="text-verdeReservas">
                
                <th class="text-verdeReservas">NOMBRES</th>
                <th class="text-verdeReservas">APELLIDOS</th>
                <th class="text-verdeReservas">CEDULA</th>
                <th class="text-verdeReservas">GENERO</th>
                <th class="text-verdeReservas">FECHA DE NACIMIENTO</th>
                <th class="text-verdeReservas">TRABAJO ACTUAL</th>
                <th class="text-verdeReservas">EXPECTATIVA SALARIAL</th>
                <th class="text-verdeReservas"></th>



            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>


@section Scripts{



    <script>
        $(document).ready(function () {


            //Convierte los botones dentro del datatable Clickeables y llaman
            //su funcion correspondiente
            $('#tbCandidatos tbody').on('click', '[id*=btnEditar]', function () {
                var row = table.row($(this).parents('tr')).data();
                var identificador = row.candidato_Id;
                console.log(identificador);
                window.open(`/Candidatos/Edit/${identificador}`, '_self');
            });

            $('#tbCandidatos tbody').on('click', '[id*=btnDetalle]', function () {
                var row = table.row($(this).parents('tr')).data();
                var identificador = row.candidato_Id;
                console.log(identificador);
                window.open(`/Candidatos/Details/${identificador}`, '_self');
            });

            $('#tbCandidatos tbody').on('click', '[id*=btnEliminar]', function () {
                var row = table.row($(this).parents('tr')).data();
                var identificador = row.candidato_Id;
                console.log(identificador);
                window.open(`/Candidatos/Delete/${identificador}`, '_self');
            });

            var table = $("#tbCandidatos").DataTable({

                language: {
                    paginate: {
                        next: 'Siguiente', // or '→'
                        previous: 'Anterior' // or '←'
                    },
                    search: "Buscar:",
                    "lengthMenu": "Mostrando _MENU_ registros por pagina",
                    "info": "Mostrando Pagina _PAGE_ de _PAGES_",
                },

                "responsive":true,

                "ajax": {
                    "url": "@Url.Action("Applicant","Candidatos")",
                    "type": "POST",
                    "datatype": "json"

                },
                "processing": false,
                "serverSide": true,
                "searching": true,
                "filter": true,
                
                


                "columns": [
                    
                    { "data": "nombres", name: "nombres" },
                    { "data": "apellidos", name: "apellidos" },
                    { "data": "cedula", name: "cedula" },
                    { "data": "genero", name: "genero" },
                    { "data": "fechaDeNacimiento", name: "fechaDeNacimiento","width":"17%" },
                    { "data": "trabajoActual", name: "trabajoActual" },
                    { "data": "expectativaSalarial", name: "expectativaSalarial"},
                    {
                        "data": null, title: 'ACCIONES', "width": "16%",
                        "render": function () { return '<div class=""><i  class="fa-solid fa-pen-to-square btn btn-verdeReservas me-2" id="btnEditar"></i><i  class="fa-solid fa-file-lines btn btn-verdeReservas me-2" id="btnDetalle"></i><i class="fa-solid fa-trash btn btn-danger" id="btnEliminar"></i></div>' }
                    },

                ]

                   
                    

            });






        });


    </script>

}